### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by brunoric** [brunoric/docker-hhvm#3]
Update the documentation with all the new images and instructions added when the milestone finish.

**Comment by shehi** [comment]
@brunoric : For CI needs, I recommend using CircleCI which supports Docker and runs on Ubuntu 14 machines. That way you can get your status badges automatically, and run your tests/builds/makes in parallel (up to 4 free parallel containers, for open-source).

**Comment by brunoric** [comment]
@shehi +1 for CircleCI. I am integrating it in my worflow for this project.
