### ISSUE TITLE
Implement an automated flow to build the images

### ISSUE THREAD

**Issue by brunoric** [brunoric/docker-hhvm#6]
As I said in the issue #5, Docker Hub, Travis-CI and CircleCI can't build HHVM due RAM memory limitations in its VMs. There is a need to figure out a solution to automatize the build flow and tests using free solutions like the others cited here.

**Comment by rybakit** [comment]
@brunoric Any progress on this?

**Comment by brunoric** [comment]
Sorry @rybakit unfortunately not. =( Any help will be very appreciated. Actually I made some tests on various open source CI services and still not found one that provides all the need functionality. In fact my next step will be provision a Jenkins machine in some of my services to do the process, but I not found the time yet.

**Comment by brunoric** [comment]
After PRs #19 and #22 this issue is resolved. The process still need some adjustments since specific build based on HHVM tags are to time consuming and they are timeouting in Circle-CI.
