### ISSUE TITLE
Tagged builds don't have supervisord installed

### ISSUE THREAD

**Issue by jaredkipe** [brunoric/docker-hhvm#9]
`docker run -it --rm brunoric/hhvm:3.9`
Results in:
`/scripts/start.sh: line 2: exec: supervisord: not found`

**Comment by brunoric** [comment]
The codebase was already fixed, I will now update the tags (both here and in Docker Hub).

**Comment by jaredkipe** [comment]
Cool, thanks.  Unfortunately, I've gone a different direction due to needing to compile a couple of extensions.
